name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Set CI environment variable to false
      - name: Set CI to false
        run: export CI=false

      # Install NPM dependencies and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6.6.1
